import asyncio
import logging
from datetime import datetime, timezone
from typing import Dict, Any

# Configure the logger according to the interface contract requirements
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("StubDetector")

class StubDetector:
    """
    A fake object detector (Stub) for Sprint 2 integration testing.
    It completely ignores the input image content and always returns 
    predefined detection results (e.g., tomatoes).
    Its primary purpose is to allow end-to-end testing of the pipeline's 
    data flow without the overhead of a real AI model.
    """
    
    def __init__(self):
        # Hardcoded mock definitions
        self.task_type = "fruit_detection"
        self.label = "tomato"
        self.confidence = 0.98
        
        # 2 example mock bounding boxes.
        # Format: [x_min, y_min, x_max, y_max] - assuming absolute pixels.
        self.hardcoded_bboxes = [
            [120, 150, 220, 250],
            [305, 100, 350, 145]
        ]

    async def process_frame(self, input_payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        The main asynchronous function that receives a frame payload from iqa_gate 
        (Stage 2) and passes the structured output to json_serializer (Stage 3).
        """
        try:
            # Force a crash if the input is completely invalid (not a dict)
            if not isinstance(input_payload, dict):
                raise ValueError("input_payload is not a valid dictionary")

            # Extract identifying metadata to maintain continuity (frame_id, robot_id)
            frame_id = input_payload.get("frame_id", -1)
            robot_id = input_payload.get("robot_id", "unknown_robot")
            
            # Generate a properly formatted ISO 8601 timestamp
            current_timestamp = datetime.now(timezone.utc).isoformat()
            
            # Assemble the array of fake inference results
            inference_results = []
            for bbox in self.hardcoded_bboxes:
                detection = {
                    "task_type": self.task_type,
                    "label": self.label,
                    "confidence": self.confidence,
                    "bbox": bbox,
                    "attributes": {
                        "is_mock": True, 
                        "note": "Generated by StubDetector - Do not use in production"
                    }
                }
                inference_results.append(detection)
                
            # Build the final output exactly as required by the Detection Payload Schema
            output_payload = {
                "frame_id": frame_id,
                "robot_id": robot_id,
                "timestamp": current_timestamp,
                "inference_results": inference_results
            }
            
            logger.debug(f"Successfully generated stub detections for frame {frame_id}")
            
            # Simulate a brief processing delay (prevents the pipeline from running too fast)
            await asyncio.sleep(0.01) 
            
            return output_payload

        except Exception as e:
            # As per contract: "Detector crash -> log error" + return empty list
            logger.error(f"StubDetector crashed while processing frame: {e}")
            
            # SAFE FALLBACK: Only try to extract metadata if input is actually a dict
            fallback_frame = -1
            fallback_robot = "unknown_robot"
            
            if isinstance(input_payload, dict):
                fallback_frame = input_payload.get("frame_id", -1)
                fallback_robot = input_payload.get("robot_id", "unknown_robot")
                
            return {
                "frame_id": fallback_frame,
                "robot_id": fallback_robot,
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "inference_results": []  # Empty detections on error
            }