import asyncio
import pprint
import logging
from stub_detector import StubDetector

# Configure logging to see the error messages generated by the crash test
logging.basicConfig(level=logging.INFO)

async def run_all_tests():
    print("🚀 Starting Comprehensive Test Suite for StubDetector...\n")
    
    # Initialize the detector once for all tests
    detector = StubDetector()

    # ==========================================
    # TEST 1: Happy Path (Normal Execution)
    # ==========================================
    print("-" * 50)
    print("🧪 TEST 1: Happy Path (Valid Input)")
    print("-" * 50)
    valid_input = {
        "frame_id": 101,
        "robot_id": "hexapod-alpha",
        "timestamp": "2026-05-27T10:00:00Z",
        "image_bytes": b"fake_binary_data",
        "encoding": "jpeg",
        "quality_score": 0.99
    }
    result_1 = await detector.process_frame(valid_input)
    pprint.pprint(result_1, sort_dicts=False)
    print("✅ TEST 1 PASSED: Detections generated successfully.\n")


    # ==========================================
    # TEST 2: Missing Fields (Graceful Degradation)
    # ==========================================
    print("-" * 50)
    print("🧪 TEST 2: Missing Metadata (No frame_id or robot_id)")
    print("-" * 50)
    # Sending a payload missing crucial identification fields
    missing_fields_input = {
        "image_bytes": b"fake_binary_data",
        "quality_score": 0.50
    }
    result_2 = await detector.process_frame(missing_fields_input)
    pprint.pprint(result_2, sort_dicts=False)
    
    # Validation check: Ensure default values were applied
    if result_2["frame_id"] == -1 and result_2["robot_id"] == "unknown_robot":
        print("✅ TEST 2 PASSED: Missing fields handled gracefully with defaults.\n")
    else:
        print("❌ TEST 2 FAILED: Defaults were not applied correctly.\n")


    # ==========================================
    # TEST 3: Extreme Crash (Failure Injection)
    # ==========================================
    print("-" * 50)
    print("🧪 TEST 3: Extreme Crash (Invalid Data Type Injection)")
    print("-" * 50)
    # Sending a string instead of a dictionary. 
    # This will cause an AttributeError when the detector tries to use '.get()'
    corrupted_input = "This is a corrupted string, not a dictionary payload!"
    
    # The detector should catch the internal crash and return an empty inference list
    result_3 = await detector.process_frame(corrupted_input)
    pprint.pprint(result_3, sort_dicts=False)
    
    # Validation check: Ensure it didn't crash the program and returned empty results
    if len(result_3["inference_results"]) == 0:
        print("✅ TEST 3 PASSED: Crash was caught, empty results returned as per contract.\n")
    else:
        print("❌ TEST 3 FAILED: System did not handle the crash properly.\n")


if __name__ == "__main__":
    # Execute the async test suite
    asyncio.run(run_all_tests())